### ISSUE TITLE
New member request

### ISSUE THREAD

**Issue by amcintoshresas** [DataScienceScotland/welcome#47]
### To join the organisation, please confirm the following:

- [X] I am a current employee of the Scottish Government
- [X] I have read and understand the [user responsibilities](https://erdm.scotland.gov.uk/documents/A42743383/details) for using GitHub in Scottish Government
- [X] I have read the guidance in the [welcome](https://github.com/DataScienceScotland/welcome) repo
- [ ] I have my gov.scot email address public on my GitHub profile
- [X] I understand I will periodically need to confirm my ongoing need for access

**Comment by alicebyers5** [comment]
Hi there - please can you made your email address public on your profile? Instructions are in the message above.
